

server:
  port: 8090

spring:
  application:
    name: SERVICE-VOITURE
  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:postgresql://postgres:5432/voitures
    username: hmayda
    password: hmayda

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
      enabled: true